### ISSUE TITLE
存在问题

### ISSUE THREAD

**Issue by TieJiang13** [2992058813/faker#3]
1.格式存在问题没对齐（美观问题）
![image](https://user-images.githubusercontent.com/52875154/74162582-f5ee6e00-4c5b-11ea-8343-9a2f68143c78.png)

2.ZH函数没有被调用，无法运行
![image](https://user-images.githubusercontent.com/52875154/74162517-df481700-4c5b-11ea-934c-f9225e1f2606.png)

**Comment by 2992058813** [comment]
好的谢谢收到

**Comment by 2992058813** [comment]
好的谢谢收到
